# NOTE: Replace only the text inside the quotes. Keep the quotes!
# Example: Host("proxy.ttgs.io")
http:
  routers:
    proxy-router:
      rule: Host("proxy.ttgs.io")
      entryPoints: ["websecure"]
      tls:
        certResolver: "letsencrypt"
      service: proxy-svc
      middlewares:
        - proxy-security
        - proxy-gzip

  services:
    proxy-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://192.168.1.231:7777"

  middlewares:
    proxy-gzip:
      compress: {}

    proxy-security:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        contentTypeNosniff: true
        referrerPolicy: "no-referrer"
        customFrameOptionsValue: "SAMEORIGIN"
