# NOTE: Replace only the text inside the quotes. Keep the quotes!
# Example: Host("node2.ttgs.io")
http:
  routers:
    node2-router:
      rule: Host("node2.ttgs.io")
      entryPoints: ["websecure"]
      tls:
        certResolver: "letsencrypt"
      service: node2-svc
      middlewares:
        - node2-security
        - node2-gzip

  services:
    node2-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://192.168.1.172:22"

  middlewares:
    node2-gzip:
      compress: {}

    node2-security:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        contentTypeNosniff: true
        referrerPolicy: "no-referrer"
        customFrameOptionsValue: "SAMEORIGIN"
