services:
  radarr:
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=000
      - TZ=America/Detroit
    volumes:
      - /configs/radarr:/config
      - /media:/media
      - /downloads:/downloads
      - /docker:/docker
    image: ghcr.io/hotio/radarr
    healthcheck:
      test:
        - CMD-SHELL
        - wget -q --spider http://127.0.0.1:7878 || exit 1
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 20s
networks:
  dockge_default:
    external: true
