# NOTE: Replace only the text inside the quotes. Keep the quotes!
# Example: Host("sonarr.ttgs.io")
http:
  routers:
    sonarr-router:
      rule: Host("sonarr.ttgs.io")
      entryPoints: ["websecure"]
      tls:
        certResolver: "letsencrypt"
      service: sonarr-svc
      middlewares:
        - sonarr-security
        - sonarr-gzip

  services:
    sonarr-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://192.168.1.231:8989"

  middlewares:
    sonarr-gzip:
      compress: {}

    sonarr-security:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        contentTypeNosniff: true
        referrerPolicy: "no-referrer"
        customFrameOptionsValue: "SAMEORIGIN"
