services:
  tautulli:
    container_name: tautulli
    restart: unless-stopped
    ports:
      - 8181:8181
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=000
      - TZ=America/Detroit
    volumes:
      - /configs/tautulli:/config
      - /media:/media
      - /downloads:/downloads
      - /docker:/docker
    image: ghcr.io/hotio/tautulli
    healthcheck:
      test:
        - CMD-SHELL
        - wget -q --spider http://127.0.0.1:8181 || exit 1
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 30s
networks:
  dockge_default:
    external: true
