# Dynamic config for Traefik (file provider)
http:
  routers:
    traefik-traefik-7777-router:
      # NOTE: Replace only the text inside the quotes. Keep the quotes!
      # Example: Host("traefik.ttgs.io")
      rule: Host("<DNS_NAME>")
      entryPoints: ["websecure"]
      tls:
        # NOTE: Replace only inside the quotes. Keep the quotes!
        # Example: "letsencrypt"
        certResolver: "<CERT_RESOLVER_NAME>"
      service: traefik-traefik-7777-svc
      middlewares:
        - traefik-security
        - traefik-gzip

  services:
    traefik-traefik-7777-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          # NOTE: Replace only <IP_ADDRESS>. Keep the quotes!
          # Example: "http://192.168.1.45:7777"
          - url: "http://<IP_ADDRESS>:7777"

  middlewares:
    traefik-gzip:
      compress: {}

    traefik-security:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        contentTypeNosniff: true
        referrerPolicy: "no-referrer"
        customFrameOptionsValue: "SAMEORIGIN"
