services:
  sonarr:
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=000
      - TZ=America/Detroit
    volumes:
      - /configs/sonarr:/config
      - /media:/media
      - /downloads:/downloads
      - /docker:/docker
    image: ghcr.io/hotio/sonarr
    healthcheck:
      test:
        - CMD-SHELL
        - wget -q --spider http://127.0.0.1:8989 || exit 1
      interval: 1m
      timeout: 5s
      retries: 3
      start_period: 20s
networks:
  dockge_default:
    external: true
