# Dynamic config for Traefik (file provider)
http:
  routers:
    sonarr-sonarr-8989-router:
      # NOTE: Replace only the text inside the quotes. Keep the quotes!
      # Example: Host("sonarr.ttgs.io")
      rule: Host("<DNS_NAME>")
      entryPoints: ["websecure"]
      tls:
        # NOTE: Replace only inside the quotes. Keep the quotes!
        # Example: "letsencrypt"
        certResolver: "<CERT_RESOLVER_NAME>"
      service: sonarr-sonarr-8989-svc
      middlewares:
        - sonarr-security
        - sonarr-gzip

  services:
    sonarr-sonarr-8989-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          # NOTE: Replace only <IP_ADDRESS>. Keep the quotes!
          # Example: "http://192.168.1.45:8989"
          - url: "http://<IP_ADDRESS>:8989"

  middlewares:
    sonarr-gzip:
      compress: {}

    sonarr-security:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        contentTypeNosniff: true
        referrerPolicy: "no-referrer"
        customFrameOptionsValue: "SAMEORIGIN"
