# NOTE: Replace only the text inside the quotes. Keep the quotes!
# Example: Host("prowlarr.ttgs.io")
http:
  routers:
    prowlarr-router:
      rule: Host("prowlarr.ttgs.io")
      entryPoints: ["websecure"]
      tls:
        certResolver: "letsencrypt"
      service: prowlarr-svc
      middlewares:
        - prowlarr-security
        - prowlarr-gzip

  services:
    prowlarr-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://192.168.1.231:9696"

  middlewares:
    prowlarr-gzip:
      compress: {}

    prowlarr-security:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        contentTypeNosniff: true
        referrerPolicy: "no-referrer"
        customFrameOptionsValue: "SAMEORIGIN"
