# NOTE: Replace only the text inside the quotes. Keep the quotes!
# Example: Host("tdarr.ttgs.io")
http:
  routers:
    tdarr-router:
      rule: Host("tdarr.ttgs.io")
      entryPoints: ["websecure"]
      tls:
        certResolver: "letsencrypt"
      service: tdarr-svc
      middlewares:
        - tdarr-security
        - tdarr-gzip

  services:
    tdarr-svc:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://192.168.1.233:8265"

  middlewares:
    tdarr-gzip:
      compress: {}

    tdarr-security:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        frameDeny: true
        contentTypeNosniff: true
        referrerPolicy: "no-referrer"
        customFrameOptionsValue: "SAMEORIGIN"
