name: Lint and Validate
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y yamllint
      - run: yamllint . -f parsable || true
      - run: echo "Validate docker-compose if Docker is available"
